### ISSUE TITLE
'latest' version does not extist

### ISSUE THREAD

**Issue by tomByrer** [theatre-js/website#14]
I have not reviewed all links in your website, but the links to `rafDrivers` go here:
https://www.theatrejs.com/docs/docs/latest/manual/advanced#rafdrivers
but the actual page is:
https://www.theatrejs.com/docs/0.5/manual/advanced#rafdrivers
So instead of `latest` pointing to `0.5`, it 404

I was about to just edit the .mdx files, but I'm not sure what your intended behavior is.
I do like the idea of 'latest', with the actual version number being in the webpage somewhere (if the browser's URL is actually `.../0.5/manual/...`, that is up to you).

TIA :)

**Comment by AriaMinaei** [comment]
Fixed via 0ce11ea. Thanks @tomByrer
